name: CI

on:
  push:
    branches:
    - main

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      with:
        terraform_version: 1.14.7
    - name: Initialise with no backend
      run: terraform init -backend=false
    - name: Check Terraform formatting
      run: terraform fmt -check -recursive
    - name: Validate Terraform configuration
      run: terraform validate
    - name: Run Terraform tests
      run: terraform test
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.14
    - name: Check Python formatting
      uses: psf/black@c6755bb741b6481d6b3d3bb563c83fa060db96c9
      with:
        src: lambda
        version: 26.3.1

  release:
    name: Release?
    needs: [ verify ]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Prepare a release
      uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
      with:
        config-file: .github/release-please-config.json
        manifest-file: .github/release-please-manifest.json
        token: ${{ secrets.GITHUB_TOKEN }}
