name: CI

on:
  push:
    branches:
    - main

jobs:
  terraform:
    name: Verify Terraform
    uses: unfunco/meta/.github/workflows/verify-terraform.yaml@80154eaeae1d18131405850847f76b27490a68f0
    with:
      run-tests: true

  verify:
    name: Verify
    needs: [ terraform ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.14
    - name: Check Python formatting
      uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e
      with:
        src: lambda
        version: 26.3.1

  release:
    name: Release?
    needs: [ verify ]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Prepare a release
      uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
      with:
        config-file: .github/release-please-config.json
        manifest-file: .github/release-please-manifest.json
        token: ${{ secrets.GITHUB_TOKEN }}
