name: CI

on:
  push:
    branches:
    - main

jobs:
  terraform:
    name: Verify Terraform
    uses: unfunco/meta/.github/workflows/verify-terraform.yaml@2cf07936a31dca1b82fe1e447f48e1580c10880e # v0.2.0
    with:
      run-tests: true

  verify:
    name: Verify
    needs: [ terraform ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: 3.14
    - name: Check Python formatting
      uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e
      with:
        src: lambda
        version: 26.3.1

  release:
    name: Release?
    needs: [ verify ]
    permissions:
      contents: write
      pull-requests: write
    uses: unfunco/meta/.github/workflows/release-please.yaml@2cf07936a31dca1b82fe1e447f48e1580c10880e # v0.2.0
